codecov:
    require_ci_to_pass: yes

coverage:
    precision: 1
    round: nearest
    range: '50...80'

ignore:
    - 'bin/*'
    - 'tests/*'
    - 'vendor/*'
    - 'node_modules/*'

comment:
    layout: 'reach, diff, flags, files'
    behavior: default
    require_changes: false
    require_base: no
    require_head: yes
    show_carryforward_flags: false
