name: Set PR Labels

on:
  pull_request_target:
    types: opened

jobs:
  SetLabels:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Set Labels
        uses: eason9487/grow/branch-label@actions-v2
