name: Build

on:
  push:
    branches:
      - trunk
      - develop
      # For temporary testing
      - dev/gh-actions-build
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  BuildExtensionBundle:
    name: Build extension bundle
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@actions-v1
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      # Since BundleWatch is having issues when getting some environment variables from GitHub Actions,
      # it needs some workarounds to specify `CI_COMMIT_SHA`, `CI_BRANCH`, and `CI_BRANCH_BASE` here.
      # References:
      # - https://github.com/bundlewatch/bundlewatch/blob/v0.3.2/src/app/config/getCIVars.js#L8-L10
      # - https://github.com/bundlewatch/bundlewatch/issues/423
      # - https://github.com/bundlewatch/bundlewatch/issues/220
      - name: Prepare BundleWatch env values - push
        # For temporary testing
        if: ${{ github.event_name == 'push' && github.ref_name != 'dev/gh-actions-build' }}
        # if: ${{ github.event_name == 'push' }}
        run: |
          BRANCH=$(echo '${{ github.event.ref }}' | sed 's/^refs\/heads\///')
          echo "CI_BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "CI_BRANCH_BASE=$BRANCH" >> $GITHUB_ENV
          echo "CI_COMMIT_SHA=${{ github.sha }}" >> $GITHUB_ENV

      - name: Prepare BundleWatch env values - pull request
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "CI_BRANCH=${{ github.head_ref }}" >> $GITHUB_ENV
          echo "CI_BRANCH_BASE=${{ github.base_ref }}" >> $GITHUB_ENV
          echo "CI_COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

      - name: Run BundleWatch
        env:
          BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
        run: node ./node_modules/bundlewatch/lib/bin/index.js

      - name: Publish dev build to GitHub
        # For temporary testing
        if: ${{ github.event_name == 'push' && github.ref_name == 'dev/gh-actions-build' }}
        uses: woocommerce/grow/publish-extension-dev-build@actions-v1
        # if: ${{ github.event_name == 'push' && github.ref_name == 'develop' }}
        # uses: woocommerce/grow/publish-extension-dev-build@actions-v1
        with:
          extension-asset-path: google-listings-and-ads.zip
