name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml
  pull_request:
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"
          install-deps: "no"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/eslint-annotation@actions-v1

      - name: Lint JavaScript and annotate linting errors
        run: |
          npm ci --ignore-scripts --cache /tmp/npm-cache-test
          npm run lint:js -- --quiet --format ./eslintFormatter.cjs
